# Pseudo config for deployment
# todo: implement using vlad or similar

tank-pi:
  deploy-path: /home/pi/water-tank-sensor-control # remote directory where app is installed
  repo: bitbucket.org/SteveBenner09/ranch-water-tank-sensor-project
  gems:
    system: # install using `sudo gem install`
      - bundler
      - rake
      - vlad
  app:
    - couchrest_model