# 'Ranch Water Tank Monitoring System' data documentation:
#
# CouchDB (single installation)
#

# Database and document schema
databases:
  readings:   # Sensor reading records
  logs:       # Logs
  admin:      # Configuration settings and persistent app data
    settings:
      # How much time to wait (in seconds) between each sensor reading
      sensor_poll_interval:
