# CouchDB database and document schema for the 'Ranch Water Tank Monitoring System'
#
# FORMAT:
# 'databases'
#    database name
#      document name
#        key level 1: data type or class (e.g. `Integer`)
#          key level N...
#
databases:
  # Sensor readings DB - exclusively for storing DistanceReading
  readings:
    _design/main:     # Primary design doc for presenting the web view
    timestamp:        # DistanceReading docs save their timestamp (ISO8601) as `_id`
      value: Integer  # Millimeters from sensor to water fill level
  # Admin DB - for managing configuration, authentication, etc.
  admin:
    system_specs: # Information and specs pertaining to the water tank and hardware system
      tank: # Manufacturer information copied directly from included PDF documentation
        manufacturer:
          name: String
          phone: String
          publication_date: String
        model: String # Tank model (according to PDF documentation)
        capacity_imp_gallons: Integer # Tank volume in Imperial Gallons
        capacity_liters: Integer # Tank volume in Liters
        diameter: Integer # Inches
    config: # Configuration values are used to determine script behavior and other app settings
      # How much time to wait between each sensor reading
      sensor_poll_interval: Integer # Seconds between each sensor read operation
      # todo: add config values for alerts (min/max/etc)
      # todo: info regarding off-site replication target
  # todo: add alerts schema
  alerts:
  # todo: add log schema
  logs: # Custom log messages (e.g. reports of failure, such as sensor script failing to return a value)
