# Data schema for water tank monitoring system data

# Single database titled 'main'
main
  config # Software configuration settings
  # Data is logged via records using sequential UUIDs
  # (32 hex char incrementing filenames)