# Copyright (C) 2024 Robert Hancock
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Robert Hancock
# https://github.com/cyberify

# Three methods for interfacing with the Maxbotix sensor:
# [1] measuring the pulse-width generated by the sensor
# [2] measuring the analog voltage produced by the sensor
# [3] reading RS232 serial data, the approach this script takes


import board
import busio
import digitalio
import adafruit_rfm69
import time
import re
import neopixel

# RFM69HCW Radio Code
RADIO_FREQ_MHZ = 915.0
CS = digitalio.DigitalInOut(board.D6)
RESET = digitalio.DigitalInOut(board.D9)
spi = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
rfm69 = adafruit_rfm69.RFM69(spi, CS, RESET, RADIO_FREQ_MHZ)
rfm69.encryption_key = ''

# Setup RGB LED
led = neopixel.NeoPixel(board.NEOPIXEL, 1)
led[0] = (0, 0, 0)

# Initialize Maxbotix Ultrasonic Sensor
ser = busio.UART(board.TX, board.RX, baudrate=9600, bits=8, parity=None, stop=1)

while True:
    # If data present in the input buffer
    if ser.in_waiting:
        # You can only send and receive packets up to 60 bytes in length at a time.
        data = ser.read(60)
        print(data)
        if rfm69.send(data):
            led[0] = (0, 255, 0)
        time.sleep(0.05)
        led[0] = (0, 0, 0)
    time.sleep(0.5)
